service: balek

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main:
    handler: ./dist/function/api/index.handler
    events:
      - http:
          path: '{proxy+}'
          method: any
